/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0f5238',
        'primary-container': '#2d6a4f',
        'on-primary': '#ffffff',
        'on-primary-container': '#a8e7c5',
        surface: '#f8faf6',
        'surface-dim': '#d8dbd7',
        'surface-bright': '#f8faf6',
        'on-surface': '#191c1a',
        'on-surface-variant': '#404943',
        outline: '#707973',
        'outline-variant': '#bfc9c1',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        secondary: '#5c5f60',
        'secondary-container': '#e1e3e4',
        'on-secondary-container': '#626566',
        tertiary: '#44484b',
        'tertiary-container': '#5c6063',
        background: '#f8faf6',
        'primary-fixed': '#b1f0ce',
        'primary-fixed-dim': '#95d4b3',
        warning: '#e8a317',
        'warning-bg': '#fef3c7',
        optimal: '#16a34a',
        'optimal-bg': '#dcfce7',
        critical: '#dc2626',
        'critical-bg': '#fee2e2',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'numeric-data': ['20px', { lineHeight: '24px', fontWeight: '700' }],
      },
      borderRadius: {
        '4': '0.25rem',
        '6': '0.375rem',
        '8': '0.5rem',
        '10': '0.625rem',
        '12': '0.75rem',
        '16': '1rem',
        '20': '1.25rem',
        'pill': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '20px',
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(0,0,0,0.05)',
        'card-hover': '0px 8px 24px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
